### ISSUE TITLE
Examples don't build

### ISSUE THREAD

**Issue by ko** [react-component/pagination#74]
Followed the README and navigated to [http://localhost:3000/examples/](http://localhost:3000/examples/) after doing the following:

```
npm install
npm start
```

There were errors while building the bundle. You'll see:

```
Listening at http://localhost:3000
10/20 build modules
webpack: bundle build is now finished.
Hash: d22b205c50dfd7328bfd
Version: webpack 1.15.0
Time: 566ms
       Asset     Size  Chunks             Chunk Names
  default.js  3.59 kB       0  [emitted]  default
   jumper.js   3.6 kB       1  [emitted]  jumper
lessPages.js  3.61 kB       2  [emitted]  lessPages
     more.js  3.59 kB       3  [emitted]  more
showTitle.js  3.61 kB       4  [emitted]  showTitle
showTotal.js  3.61 kB       5  [emitted]  showTotal
   simple.js   3.6 kB       6  [emitted]  simple
    sizer.js   3.6 kB       7  [emitted]  sizer
   stupid.js  3.61 kB       8  [emitted]  stupid
   styles.js  3.61 kB       9  [emitted]  styles
chunk    {0} default.js (default) 28 bytes [rendered]
    [0] multi default 28 bytes {0} [built] [1 error]
chunk    {1} jumper.js (jumper) 28 bytes [rendered]
    [0] multi jumper 28 bytes {1} [built] [1 error]
chunk    {2} lessPages.js (lessPages) 28 bytes [rendered]
    [0] multi lessPages 28 bytes {2} [built] [1 error]
chunk    {3} more.js (more) 28 bytes [rendered]
    [0] multi more 28 bytes {3} [built] [1 error]
chunk    {4} showTitle.js (showTitle) 28 bytes [rendered]
    [0] multi showTitle 28 bytes {4} [built] [1 error]
chunk    {5} showTotal.js (showTotal) 28 bytes [rendered]
    [0] multi showTotal 28 bytes {5} [built] [1 error]
chunk    {6} simple.js (simple) 28 bytes [rendered]
    [0] multi simple 28 bytes {6} [built] [1 error]
chunk    {7} sizer.js (sizer) 28 bytes [rendered]
    [0] multi sizer 28 bytes {7} [built] [1 error]
chunk    {8} stupid.js (stupid) 28 bytes [rendered]
    [0] multi stupid 28 bytes {8} [built] [1 error]
chunk    {9} styles.js (styles) 28 bytes [rendered]
    [0] multi styles 28 bytes {9} [built] [1 error]
```

All of them have the same error. I've pasted the backtrace for default.js as a reference: 

```
ERROR in ./examples/default.js
Module build failed: Error: Couldn't find preset "latest" relative to directory "/Users/kenko/src"
    at /Users/kenko/src/pagination/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/kenko/src/pagination/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/kenko/src/pagination/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/kenko/src/pagination/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/kenko/src/pagination/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/kenko/src/pagination/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/kenko/src/pagination/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/kenko/src/pagination/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/kenko/src/pagination/node_modules/babel-loader/lib/index.js:46:20)
 @ multi default
```

From what I can tell, we want to include [babel-preset-latest](https://babeljs.io/docs/plugins/preset-latest/). However, that appears to be deprecated for [babel-preset-env](https://babeljs.io/docs/plugins/preset-env/#usage).

**Comment by paranoidjk** [comment]
we haven't use  babel-preset-latest, please check your code.

**Comment by ko** [comment]
I didn't see use of babel-preset-latest. This is just what I encountered immediately after a 

```
git co
npm i
npm start
```

I don't see anything babel related with an `npm ls -g`, thinking that that could be a possibility for interfering.

**Comment by paranoidjk** [comment]
what's your nodejs and npm version ? do you install webpack globally?

**Comment by benjycui** [comment]
I don't understand, this works fine on our computer.

So, please provide more information about your environment, OS and npm and node.js and so on.

**Comment by ko** [comment]
Wow. Sorry. 

I found a `.babelrc` in a parent directory. Removing that resolves the issue. 

Thanks!
